### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by elektron-bbs** [fhem/Timer#4]
Kann es sein, das hier die Datei ".gitattributes" fehlt?
Siehe z.B.:
https://github.com/RFD-FHEM/RFFHEM/blob/master/.gitattributes

**Comment by HomeAutoUser** [comment]
Wenn ich die Beschreibung hier

https://help.github.com/en/articles/configuring-git-to-handle-line-endings

lese, so kann es sein.

# Explicitly declare text files you want to always be normalized and 
converted
# to native line endings on checkout.

sagt aus:

Deklarieren Sie explizit Textdateien, die Sie normalisieren und konvertieren möchten
zu nativen Zeilenenden beim Auschecken.

------ Originalnachricht ------
Von: "Udo" <notifications@github.com>
An: "fhem/Timer" <Timer@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 17.10.2019 17:55:19
Betreff: [fhem/Timer] Line endings (#4)

**Comment by elektron-bbs** [comment]
Ich habe es eben bei mir https://github.com/elektron-bbs/Timer getestet.
Mit der Datei bleiben die Zeilenenden auf Linux.
Die kannst die Datei direkt in deinem Github-Desktop in den Repository-Settings erstellen.

**Comment by HomeAutoUser** [comment]
*lach*

nun habe ich erstmals ausversehen hier geantwortet via E-Mailfunktion im oberen Post.

Die Antwort hast du sicherlich schon via Mail erhalten. Ich habe die Dateien mit 
https://github.com/fhem/Timer/commit/a8c4b8b29682a00cc57e88906a7dc4f210c1710a und https://github.com/fhem/Timer/commit/085acc949bbea18d5df1f4e081aa87d4de774126 hinzugefügt. Über eine genauere Einschränkung der FileTypen könnte man nun noch diskutieren.

**Comment by elektron-bbs** [comment]
Da hier sowieso nur ein Perl-Modul liegt, sollte das mehr als ausreichend sein.
