### ISSUE TITLE
Update, obwohl keine Änderungen

### ISSUE THREAD

**Issue by elektron-bbs** [fhem/Timer#9]
@HomeAutoUser 
Hast du eine Idee, warum die Datei "88_Timer.pm" immer wieder herunter geladen wird, obwohl es keine Änderungen gab? Ich beobachte das schon seit geraumer Zeit auf mehreren Systemen.

```
2020.03.25 17:06:33 1: Downloading https://raw.githubusercontent.com/fhem/Timer/pre-release/controls_Timer.txt
2020.03.25 17:06:33 1: 
2020.03.25 17:06:33 1: Timer
2020.03.25 17:06:34 1: UPD FHEM/88_Timer.pm
2020.03.25 17:06:34 1: saving fhem.cfg
2020.03.25 17:06:34 1: saving ./log/fhem.save
2020.03.25 17:06:34 1: 
2020.03.25 17:06:34 1: New entries in the CHANGED file:
2020.03.25 17:06:34 1: 2020-02-18 - Update 88_Timer.pm
2020.03.25 17:06:34 1: 
2020.03.25 17:06:34 1: Downloading https://raw.githubusercontent.com/RFD-FHEM/SIGNALduino_TOOL/pre-release/controls_SD_TOOL.txt
2020.03.25 17:06:34 1: 
2020.03.25 17:06:34 1: SD_TOOL
2020.03.25 17:06:35 1: UPD FHEM/88_SIGNALduino_TOOL.pm
2020.03.25 17:06:35 1: UPD FHEM/lib/SD_Device_ProtocolList.json
2020.03.25 17:06:35 1: saving fhem.cfg
2020.03.25 17:06:35 1: saving ./log/fhem.save
2020.03.25 17:06:35 1: 
2020.03.25 17:06:35 1: New entries in the CHANGED file:
2020.03.25 17:06:35 1: 2020-03-24 - Update 88_SIGNALduino_TOOL.pm
2020.03.25 17:06:35 1: 
2020.03.25 17:06:35 1: Downloading https://raw.githubusercontent.com/fhem/SD_Keeloq/pre-release/controls_SD_Keeloq.txt
2020.03.25 17:06:35 1: 
2020.03.25 17:06:36 1: SD_Keeloq
2020.03.25 17:06:36 1: nothing to do...

```

**Comment by HomeAutoUser** [comment]
Ich habe eine Vermutung.
Diese kann ich nur widerlegen wenn das morgige FHEM update durchlaufen ist.

Im SVN war eine etwas "ältere" Version als im PreRelease was stabil läuft.
Ich tippe, das vielleicht erst das "normale" update die Datei herunter geladen hatte und dann die von Github kam.

Auf jedenfall sind gerade alle automatischen Anpassungen nochmal durchlaufen in Github weil die aktuelle SVN Nummer angepasst wurde.

Gib einfach nochmal Bescheid.

**Comment by elektron-bbs** [comment]
Das könnte sein. Das Update aus dem SVN läuft hier zuerst und da wurde die Datei auch herunter geladen. Ich beobachte das mal weiter.
